version: "3.8"

services:
  app:
    build: ./server/book_backend
    env_file:
      - ./server/book_backend/.env
    ports:
      - "8000:8000"


  database:
    image: postgres:12
    env_file:
      - ./server/book_backend/.env
    ports:
      - "5432:5432"

