version: "3.7"

services:
  app:
    build: ./server
    env_file:
      - ./server/book_backend/venv/venv/.env
    ports:
      - "8000:8000"


  database:
    image: postgres:12
    env_file:
      - ./server/book_backend/venv/venv/.env
    ports:
      - "5432:5432"
