[tool.poetry]
name = "venv"
version = "0.1.0"
description = ""
authors = ["Said Magomedow mail:saidmagom@mail.ru"]

[tool.poetry.dependencies]
python = "^3.9"
anyio = "3.4.0"
arrow = "1.2.1"
asgiref = "3.4.1"
binaryornot = "0.4.4"
certifi = "2021.10.8"
chardet = "4.0.0"
charset-normalizer = "2.0.9"
click = "8.0.3"
cookiecutter = "1.7.3"
dnspython = "2.1.0"
email-validator = "1.1.3"
fastapi = "0.70.0"
greenlet = "1.1.2"
h11 = "0.12.0"
idna = "3.3"
Jinja2 = "3.0.3"
jinja2-time = "0.2.0"
manage-fastapi = "1.1.1"
MarkupSafe = "2.0.1"
poyo = "0.5.0"
prompt-toolkit = "3.0.23"
pydantic = "1.8.2"
python-dateutil = "2.8.2"
python-slugify = "5.0.2"
questionary = "1.10.0"
requests = "2.26.0"
six = "1.16.0"
sniffio = "1.2.0"
SQLAlchemy = "1.4.27"
starlette = "0.16.0"
text-unidecode = "1.3"
typer = "0.4.0"
typing-extensions = "4.0.1"
urllib3 = "1.26.7"
uvicorn = "0.15.0"
wcwidth = "0.2.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
